### ISSUE TITLE
RS485 types

### ISSUE THREAD

**Issue by Spookster** [dxoverdy/Alpha2MQTT#13]
Would a smaller 3485 module such as this work?
![image](https://github.com/dxoverdy/Alpha2MQTT/assets/982535/dba37320-12f4-4ec7-a116-cfdeafcb53a8)

Im thinking purely from a smaller form factor

**Comment by dxoverdy** [comment]
I see no reason why not, go for it.

**Comment by dc42** [comment]
You will need to connect the EN pin of the board to pin D5 of the ESP. Other than that, I think it should work.

The reason is that the board you pictured really does use a MAX3485 chip, whereas the larger red PCBs pictured in this project don't! They use a a MAX13487E chip. That chip has an auto transmit/receive mechanism built into it, whereas the MAX3485 doesn't. Incidentally, the MAX13487 chip is intended for 5V operation, not 3.3V; so ideally anyone using the red board should power it from 5V and use a potential divider between the TXD pin on the red board (which is the receiver output, so should really be called RXD IMO) and the ESP8266 pin to reduce the signal level to 3.3V.

**Comment by Spookster** [comment]
Good information thanks!
Yes, EN to D5 does indeed work

**Comment by Spookster** [comment]
What I ended up with for now. I had to make do with the only rj45 that was available

![image](https://github.com/dxoverdy/Alpha2MQTT/assets/982535/b2c6a71d-68d5-4aa3-94c1-6577d104be4f)

![image](https://github.com/dxoverdy/Alpha2MQTT/assets/982535/aea60616-2f41-481f-a5c1-f44c8ce85f48)

![image](https://github.com/dxoverdy/Alpha2MQTT/assets/982535/d5748b30-e14f-48ef-86d0-0d7f3b84347f)
